### ISSUE TITLE
Observing Bookie restart / CrashLoopBackOff with BookieException$InvalidCookieException

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega-operator#134]
While running moderate IO workload (10 writters, 10 readers and 100 streams with 1000 bytes size and 100 events per sec) observed bookie restart or CrashLoopBackOff on PKS environment.

Environment details: PKS / K8 with medium cluster:
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend

Pravega version: 0.5.0-2151.2e8f0b7
Zookeeper Operator : 0.2.1
Pravega Operator: 0.3.0-1

```
NAMESPACE     NAME                                                 READY     STATUS             RESTARTS   AGE
default       example-0                                            1/1       Running            0          1h
default       example-1                                            1/1       Running            0          1h
default       example-2                                            1/1       Running            0          1h
default       pravega-benchmark1                                   1/1       Running            0          50m
default       pravega-benchmark2                                   1/1       Running            0          44m
default       pravega-benchmark3                                   1/1       Running            0          44m
default       pravega-benchmark4                                   1/1       Running            0          44m
default       pravega-benchmark5                                   1/1       Running            0          43m
default       pravega-bookie-0                                     1/1       Running            0          1h
default       pravega-bookie-1                                     0/1       Running            8          1h
default       pravega-bookie-2                                     0/1       CrashLoopBackOff   10         1h
default       pravega-bookie-3                                     1/1       Running            0          1h
default       pravega-operator-577d9b49-qtjxn                      1/1       Running            0          1h
default       pravega-pravega-controller-58f7f5658b-56lww          1/1       Running            0          1h
default       pravega-pravega-controller-58f7f5658b-vcb8g          1/1       Running            0          1h
default       pravega-pravega-segmentstore-0                       1/1       Running            0          1h
default       pravega-pravega-segmentstore-1                       1/1       Running            0          59m
default       pravega-pravega-segmentstore-2                       1/1       Running            0          58m
```

Bookie Logs showing exception:
```
19-03-12 13:42:27,352 - INFO  - [main-SendThread(example-client.default.svc.cluster.local:2181):ClientCnxn$SendThread@1303] - Session establishment complete on server example-client.default.svc.cluster.local/10.100.200.114:2181, sessionid = 0x1001f770d67028d, negotiated timeout = 10000
2019-03-12 13:42:27,502 - INFO  - [main-EventThread:ZooKeeperWatcherBase@130] - ZooKeeper client is connected now.
2019-03-12 13:42:28,624 - ERROR - [main:Bookie@471] - There are directories without a cookie, and this is neither a new environment, nor is storage expansion enabled. Empty directories are [/bk/index/current]
2019-03-12 13:42:28,624 - INFO  - [main:BookieNettyServer@396] - Shutting down BookieNettyServer
2019-03-12 13:42:28,639 - ERROR - [main:Main@221] - Failed to build bookie server
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException:
        at org.apache.bookkeeper.bookie.Bookie.checkEnvironmentWithStorageExpansion(Bookie.java:475)
        at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:257)
        at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:641)
        at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:131)
        at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:100)
        at org.apache.bookkeeper.server.service.BookieService.<init>(BookieService.java:43)
        at org.apache.bookkeeper.server.Main.buildBookieServer(Main.java:299)
        at org.apache.bookkeeper.server.Main.doMain(Main.java:219)
        at org.apache.bookkeeper.server.Main.main(Main.java:201)```

**Comment by adrianmo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BookKeeper errors on Kubernetes](https://trello.com/c/ihm5UFIc/147-bookkeeper-errors-on-kubernetes)
