### ISSUE TITLE
Observed Bookie restart with exception java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by sumit-bm** [pravega/pravega-operator#137]
While running moderate IO workload (10 writters, 10 readers and 100 streams with 1000 bytes size and 100 events per sec) observed one bookie (bokie3) restart with exception java.lang.OutOfMemoryError: Java heap space on PKS environment.

Environment details: PKS / K8 with medium cluster:
3 master: xlarge: 4 CPU, 16 GB Ram, 32 GB Disk
5 worker: 2xlarge: 8 CPU, 32 GB Ram, 64 GB Disk
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend

Pravega version: 0.5.0-2151.2e8f0b7
Zookeeper Operator : 0.2.1
Pravega Operator: adrianmo/pravega-operator:issue-134

```
NAMESPACE     NAME                                                 READY     STATUS      RESTARTS   AGE
default       example-0                                            1/1       Running     0          2h
default       example-1                                            1/1       Running     0          2h
default       example-2                                            1/1       Running     0          2h
default       pravega-benchmark1                                   1/1       Running     0          1h
default       pravega-benchmark2                                   1/1       Running     0          1h
default       pravega-benchmark3                                   1/1       Running     0          1h
default       pravega-benchmark4                                   1/1       Running     0          1h
default       pravega-benchmark5                                   1/1       Running     0          1h
default       pravega-bookie-0                                     1/1       Running     0          1h
default       pravega-bookie-1                                     1/1       Running     0          1h
default       pravega-bookie-2                                     1/1       Running     0          1h
default       pravega-bookie-3                                     1/1       Running     1          1h
default       pravega-operator-f7d987f74-2mrft                     1/1       Running     0          1h
default       pravega-pravega-controller-58f7f5658b-mrvdz          1/1       Running     0          1h
default       pravega-pravega-controller-58f7f5658b-rpqfz          1/1       Running     0          1h
default       pravega-pravega-segmentstore-0                       1/1       Running     0          1h
default       pravega-pravega-segmentstore-1                       1/1       Running     0          1h
default       pravega-pravega-segmentstore-2                       1/1       Running     0          1h
default       shaka-zulu-nfs-client-provisioner-59d7f8f84c-wdh95   1/1       Running     0          2h
default       zookeeper-operator-5fcf9497f5-z5bnw                  1/1       Running     0          2h
```

Log:
```
2019-03-13 10:33:05,184 - INFO  - [ZKC-connect-executor-0:ZooKeeperClient$1$1@130] - ZooKeeper session 1000052f01f050a is created to 10.100.200.137:2181.
2019-03-13 10:33:16,839 - WARN  - [ZKC-connect-executor-0-SendThread(example-client.default.svc.cluster.local:2181):ClientCnxn$SendThread@1112] - Client session timed out, have not heard from server in 11655ms for sessionid 0x1000052f01f050a
2019-03-13 10:33:16,839 - INFO  - [ZKC-connect-executor-0-SendThread(example-client.default.svc.cluster.local:2181):ClientCnxn$SendThread@1160] - Client session timed out, have not heard from server in 11655ms for sessionid 0x1000052f01f050a, closing socket connection and attempting reconnect
2019-03-13 10:33:16,839 - ERROR - [BookieJournal-3181:BookieCriticalThread@41] - Uncaught exception in thread BookieJournal-3181 and is exiting!
java.lang.OutOfMemoryError: Java heap space
2019-03-13 10:33:16,867 - ERROR - [ForceWriteThread:Journal$ForceWriteThread@494] - I/O exception in ForceWrite thread
java.nio.channels.ClosedChannelException
        at sun.nio.ch.FileChannelImpl.ensureOpen(FileChannelImpl.java:110)
        at sun.nio.ch.FileChannelImpl.force(FileChannelImpl.java:379)
        at org.apache.bookkeeper.bookie.BufferedChannel.forceWrite(BufferedChannel.java:201)
        at org.apache.bookkeeper.bookie.JournalChannel.forceWrite(JournalChannel.java:256)
        at org.apache.bookkeeper.bookie.Journal$ForceWriteRequest.process(Journal.java:359)
        at org.apache.bookkeeper.bookie.Journal$ForceWriteThread.run(Journal.java:480)
2019-03-13 10:33:18,030 - INFO  - [ZKC-connect-executor-0-EventThread:ZooKeeperWatcherBase@134] - ZooKeeper client is disconnected from zookeeper now, but it is OK unless we received EXPIRED event.```

**Comment by adrianmo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [BookKeeper errors on Kubernetes](https://trello.com/c/ihm5UFIc/147-bookkeeper-errors-on-kubernetes)
