### ISSUE TITLE
Observing controller restart with error "io.pravega.controller.store.host.HostStoreException: Failed to fetch segment container map from zookeeper"

### ISSUE THREAD

**Issue by vedanthh** [pravega/pravega-operator#138]
**While running moderate IO workload in Longevity run(Total - 17 readers, 14 writers, 2500 events/sec, ~ 20 MB/s IO) Observing controller restart with error "io.pravega.controller.store.host.HostStoreException: Failed to fetch segment container map from zookeeper" after ~1 day** 

**Environment details: PKS / K8 with medium cluster:**
```
3 master nodes @ large.cpu (4 CPU, 4 GB Ram, 16 GB Disk)
5 worker nodes @ xlarge.cpu(8 cpu, 8 GB Ram, 32 GB Disk)
Tier-1 storage is from VSAN datastore
Tier-2 storage curved on NFS Client provisioner using Isilon as backend
```

[pravega-k8s-logging-2019-03-17-03-46-18.zip](https://github.com/pravega/pravega-operator/files/2976633/pravega-k8s-logging-2019-03-17-03-46-18.zip)

Pravega version: zk-closed-client-issue-0.5.0-2155.b68e912
Zookeeper Operator : pravega/zookeeper-operator:0.2.1
Pravega Operator: adrianmo/pravega-operator:issue-134-5

```[root@manager1 ~]# kubectl get po
NAME                                                 READY     STATUS    RESTARTS   AGE
pravega-zk-0                                            1/1       Running   0          4d
pravega-zk-1                                            1/1       Running   0          4d
pravega-zk-2                                            1/1       Running   0          4d
pravega-bookie-0                                     1/1       Running   1          4d
pravega-bookie-1                                     1/1       Running   0          4d
pravega-bookie-2                                     1/1       Running   0          4d
pravega-bookie-3                                     1/1       Running   0          4d
pravega-operator-577d9b49-qhw7v                      1/1       Running   0          4d
pravega-pravega-controller-58f7f5658b-jqc52          1/1       Running   3          4d
pravega-pravega-controller-58f7f5658b-kmm7r          1/1       Running   4          4d
pravega-pravega-segmentstore-0                       1/1       Running   0          4d
pravega-pravega-segmentstore-1                       1/1       Running   0          4d
pravega-pravega-segmentstore-2                       1/1       Running   0          4d
pravega-pravega-segmentstore-3                       1/1       Running   0          4d
shaka-zulu-nfs-client-provisioner-59d7f8f84c-np8q9   1/1       Running   0          4d
zookeeper-operator-5fcf9497f5-z9q2g                  1/1       Running   0          4d
```
Controller log error:
```
Caused by: io.pravega.controller.store.host.HostStoreException: Failed to fetch segment container map from zookeeper
        at io.pravega.controller.store.host.ZKHostStore.getCurrentHostMap(ZKHostStore.java:81)
        at io.pravega.controller.store.host.ZKHostStore.getHostForContainer(ZKHostStore.java:106)
        at io.pravega.controller.store.host.ZKHostStore.getHostForSegment(ZKHostStore.java:125)
        at io.pravega.controller.server.SegmentHelper.getSegmentUri(SegmentHelper.java:70)
        at io.pravega.controller.server.ControllerService.getURI(ControllerService.java:275)
        at io.pravega.controller.server.eventProcessor.LocalController.getEndpointForSegment(LocalController.java:387)
        at io.pravega.client.netty.impl.RawClient.<init>(RawClient.java:81)
        at io.pravega.client.segment.impl.SegmentMetadataClientImpl.getConnection(SegmentMetadataClientImpl.java:94)
        at io.pravega.client.segment.impl.SegmentMetadataClientImpl.getPropertyAsync(SegmentMetadataClientImpl.java:128)
        at io.pravega.client.segment.impl.SegmentMetadataClientImpl.lambda$fetchProperty$6(SegmentMetadataClientImpl.java:175)
        at io.pravega.common.concurrent.Futures.lambda$delayedFuture$21(Futures.java:536)
        at java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:981)
        at java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2124)
        at io.pravega.common.concurrent.Futures.delayedFuture(Futures.java:536)
        at io.pravega.common.util.Retry$RetryAndThrowBase.lambda$runAsync$7(Retry.java:237)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:712)
        at io.pravega.common.concurrent.Futures$Loop.call(Futures.java:681)
        at io.pravega.common.concurrent.Futures.runOrFail(Futures.java:572)
        at io.pravega.common.concurrent.Futures$Loop.run(Futures.java:725)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 common frames omitted```

**Comment by RaulGracia** [comment]
As this looks as a Controller issue, reported also here: https://github.com/pravega/pravega/issues/3477

**Comment by adrianmo** [comment]
Closing this issue based on @RaulGracia's comment above.

**Comment by sumit-bm** [comment]
I think we should close issue after it is verified, in that aspect let issue raised in Pravega space fix the issue we see and then let it get verified and then submitter could close it.

**Comment by RaulGracia** [comment]
Have you verified if this issue has been reproduced? (specially with a Pravega version including #3682)

**Comment by adrianmo** [comment]
Closing this issue as it was fixed in https://github.com/pravega/pravega/pull/3481. @vedanthh please reopen this issue if you keep experiencing problems.
