### ISSUE TITLE
Unable to set cacheMaxSize via Pravega Operator

### ISSUE THREAD

**Issue by RaulGracia** [pravega/pravega-operator#293]
### Description

 I found the following problem when changing the value of pravegaservice.cacheMaxSize via the operator. Maybe is a general parsing issue of the configuration, but I haven't see that before:
```
(CONFIGURATION)
...
      bookkeeper.bkAckQuorumSize: "3"
      # While these are low setting for RocksDB in terms of space/memory, we have verified that they make the Segment Store stable in the long run.
      pravegaservice.cacheMaxSize: "3221225472‬"
      pravegaservice.cacheMaxTimeSeconds: "600"
      rocksdb.writeBufferSizeMB: "64"
...

(LOGS IN SEGMENTSTORE)
2019-10-13 16:01:36,153 320  [main] ERROR i.p.s.server.host.ServiceStarter - Could not create a Service with default config, Aborting.
io.pravega.common.util.InvalidPropertyValueException: Value '3221225472‬' is invalid for property 'pravegaservice.cacheMaxSize'.
        at io.pravega.common.util.TypedProperties.tryGet(TypedProperties.java:144)
        at io.pravega.common.util.TypedProperties.getLong(TypedProperties.java:92)
        at io.pravega.segmentstore.server.store.ServiceConfig.<init>(ServiceConfig.java:320)
        at io.pravega.common.util.ConfigBuilder.build(ConfigBuilder.java:116)
        at io.pravega.segmentstore.server.store.ServiceBuilderConfig.getConfig(ServiceBuilderConfig.java:69)
        at io.pravega.segmentstore.server.host.ServiceStarter.<init>(ServiceStarter.java:59)
        at io.pravega.segmentstore.server.host.ServiceStarter.main(ServiceStarter.java:218)
Caused by: java.lang.NumberFormatException: For input string: "3221225472‬"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Long.parseLong(Long.java:589)
        at java.lang.Long.parseLong(Long.java:631)
        at io.pravega.common.util.TypedProperties.tryGet(TypedProperties.java:142)
        ... 6 common frames omitted
```

### Importance

Blocker (we cannot configure the cache size of the Segment Store).

### Location

Configuration of the Segment Store (`cacheMaxSize`).

### Suggestions for an improvement

Understand and fix why this particular property is not correctly set via the operator.

**Comment by pbelgundi** [comment]
@RaulGracia From above code snippets, I see that the exception occurs in segment store logs. Was any exception noticed in operator logs when deploying this manifest?
Could you please provide operator and Segment Store logs for this installation?

The job of the operator is to translate whatever is provided under "options" tag in the manifest to command line java system properties for the segment store process and that from above logs that seems to have happened correctly.
```
io.pravega.common.util.InvalidPropertyValueException: Value '3221225472‬' is invalid for property 'pravegaservice.cacheMaxSize'
```
Error in parsing the provided value should be a segment store issue rather than an operator issue.

**Comment by ravisharda** [comment]
There seems to be a non-digit (perhaps non-printable) character in the end, which must be causing this issue: `3221225472\u202C`

**Comment by RaulGracia** [comment]
You are right @ravisharda, it was indeed an invisible character that was in my manifest and I did not realize. The root cause has been to "copy" the cache size from the calculator; when I manually typed the cache size, it worked:
`2019-10-29 09:46:29,358 363  [main] INFO  i.p.s.server.host.ServiceStarter - pravegaservice.cacheMaxSize = 7156192768`
It is my fault, closing the issue.
