### ISSUE TITLE
Bookkeeper's ledger & journal volumes are not getting cleanup after destroying Pravega cluster

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#78]
After destroying Pravega Cluster, Bookkeeper volumes have not been cleaned up, so they contain data from older deployments. Due to the stale volumes present, new deployment of bookie pods are failing with below error

```
2018-10-31 10:27:44,400 - INFO  - [main-SendThread(10.100.200.42:2181):ClientCnxn$SendThread@1381] - Session establishment complete on server 10.100.200.42/10.100.200.42:2181, sessionid = 0x1000384e32b00a7, negotiated timeout = 10000
2018-10-31 10:27:44,402 - INFO  - [main-EventThread:ZooKeeperWatcherBase@131] - ZooKeeper client is connected now.
2018-10-31 10:27:44,491 - INFO  - [main:BookieNettyServer@382] - Shutting down BookieNettyServer
2018-10-31 10:27:44,497 - ERROR - [main:BookieServer@435] - Exception running bookie server :
org.apache.bookkeeper.bookie.BookieException$InvalidCookieException: Cookie [4
bookieHost: "10.200.84.29:3181"
journalDir: "/bk/journal"
ledgerDirs: "1\t/bk/ledgers"
instanceId: "f3db659f-6039-4399-b76e-8d5bedbf2bd7"
] is not matching with [4
bookieHost: "10.200.59.7:3181"
journalDir: "/bk/journal"
ledgerDirs: "1\t/bk/ledgers"
instanceId: "f3db659f-6039-4399-b76e-8d5bedbf2bd7"
]
       at org.apache.bookkeeper.bookie.Cookie.verifyInternal(Cookie.java:141)
        at org.apache.bookkeeper.bookie.Cookie.verify(Cookie.java:152)
        at org.apache.bookkeeper.bookie.Bookie.checkEnvironment(Bookie.java:329)
        at org.apache.bookkeeper.bookie.Bookie.<init>(Bookie.java:687)
        at org.apache.bookkeeper.proto.BookieServer.newBookie(BookieServer.java:124)
        at org.apache.bookkeeper.proto.BookieServer.<init>(BookieServer.java:100)
        at org.apache.bookkeeper.proto.BookieServer.main(BookieServer.java:418)
```

**Comment by adrianmo** [comment]
I've been investigating this behavior and apparently it's a design decision of the K8 `StatefulSet` resource. 

From the [official documentation](https://kubernetes.io/docs/tasks/run-application/delete-stateful-set/#persistent-volumes): 

> Deleting the Pods in a StatefulSet will not delete the associated volumes. This is to ensure that you have the chance to copy data off the volume before deleting it. Deleting the PVC after the pods have left the terminating state might trigger deletion of the backing Persistent Volumes depending on the storage class and reclaim policy. You should never assume ability to access a volume after claim deletion.

The question now is: do we want to honor this design decision or we want the operator to clean up all claims and volumes when a cluster is deleted?

ping @fpj @deenav @arvindkandhare @sumit-bm

**Comment by sumit-bm** [comment]
Could we have an extra option if we could clean-up (if reqd) using that? Then we would honor official design decision as well as there would be one way to clean up all claims and volumes (if situation needs).

**Comment by EronWright** [comment]
Seems reasonable to me that the operator would delete the volumes when the cluster is deleted.   The cluster resource could include a cleanup policy if we want the user to have control.

 Alternately a tool or script could be developed.

**Comment by adrianmo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Operator: PVC cleanup when deleting PravegaCluster](https://trello.com/c/0OFZh615/46-operator-pvc-cleanup-when-deleting-pravegacluster)
