### ISSUE TITLE
`WRONG_HOST` error when redeploying a Pravega cluster

### ISSUE THREAD

**Issue by adrianmo** [pravega/pravega-operator#91]
### Problem description

When a `PravegaCluster` is destroyed (including PVC) and recreated, a client is unable to communicate with Pravega because the wire protocols returns a `WRONG_HOST` error.

Client error log:
```
root@osboxes:~/pravega-benchmark# ./pravega-benchmark/bin/pravega-benchmark --controller tcp://35.224.63.65:9090 --stream deena -producers 1 --writeonly false --randomkey true --size 100 -eventspersec 3000 --runtime 120                                                       
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 35.224.63.65:9090
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 35.224.63.65:9090
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=9068382028951886715] Tagging client request (createScope-Scope).
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/35.224.63.65:9090], attrs={}]]
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=9068382028951886715] Scope already exists: Scope
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope/stream: Scope/deena with configuration: StreamConfiguration(scope=Scope, streamName=deena, scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null)
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=7124903224377586204] Tagging client request (createStream-Scope-deena).
[grpc-default-executor-0] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=7124903224377586204] Stream already exists: deena
[pool-1-thread-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/35.224.63.65:9090], attrs={}]]
Current segments of the stream: deena = 1
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ClientFactoryImpl - Creating writer for stream: deena with configuration: EventWriterConfig(initalBackoffMillis=1, maxBackoffMillis=20000, retryAttempts=10, backoffMultiple=10, transactionTimeoutTime=29999)
[main] INFO io.pravega.client.stream.impl.SegmentSelector - Refreshing segments for stream StreamImpl(scope=Scope, streamName=deena)
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Fetching endpoint for segment Scope/deena/0.#epoch.0, writerID: 47400b05-b22a-4e46-a11d-95567624fabb
[clientInternal-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Establishing connection to PravegaNodeUri(endpoint=35.226.135.109, port=12345) for Scope/deena/0.#epoch.0, writerID: 47400b05-b22a-4e46-a11d-95567624fabb
[epollEventLoopGroup-5-1] INFO io.pravega.client.netty.impl.ClientConnectionInboundHandler - Connection established ChannelHandlerContext(ClientConnectionInboundHandler#0, [id: 0x8bde197e]) 
[epollEventLoopGroup-5-1] INFO io.pravega.shared.protocol.netty.FailingReplyProcessor - Received hello: WireCommands.Hello(type=HELLO, highVersion=6, lowVersion=5)
[epollEventLoopGroup-5-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Failing connection for writer 47400b05-b22a-4e46-a11d-95567624fabb with exception io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=1, segment=Scope/deena/0.#epoch.0, correctHost=, serverStackTrace=)
[epollEventLoopGroup-5-1] INFO io.pravega.client.segment.impl.SegmentOutputStreamImpl - Handling exception io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=1, segment=Scope/deena/0.#epoch.0, correctHost=, serverStackTrace=) for connection io.pravega.client.netty.impl.ClientConnectionInboundHandler@16c96abe on writer 47400b05-b22a-4e46-a11d-95567624fabb. SetupCompleted: false, Closed: false
[epollEventLoopGroup-5-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - Connection for segment Scope/deena/0.#epoch.0 on writer 47400b05-b22a-4e46-a11d-95567624fabb failed due to: WireCommands.WrongHost(type=WRONG_HOST, requestId=1, segment=Scope/deena/0.#epoch.0, correctHost=, serverStackTrace=)
[epollEventLoopGroup-5-1] WARN io.pravega.client.segment.impl.SegmentOutputStreamImpl - 47400b05-b22a-4e46-a11d-95567624fabb Failed to connect: 
java.util.concurrent.CompletionException: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=1, segment=Scope/deena/0.#epoch.0, correctHost=, serverStackTrace=)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:874)
        at java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:852)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.failConnection(SegmentOutputStreamImpl.java:202)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$State.access$700(SegmentOutputStreamImpl.java:94)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.failConnection(SegmentOutputStreamImpl.java:514)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl.access$500(SegmentOutputStreamImpl.java:70)
        at io.pravega.client.segment.impl.SegmentOutputStreamImpl$ResponseProcessor.wrongHost(SegmentOutputStreamImpl.java:291)
        at io.pravega.shared.protocol.netty.WireCommands$WrongHost.process(WireCommands.java:118)
        at io.pravega.shared.protocol.netty.ReplyProcessor.process(ReplyProcessor.java:20)
        at io.pravega.client.netty.impl.ClientConnectionInboundHandler.channelRead(ClientConnectionInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.pravega.shared.protocol.netty.ExceptionLoggingHandler.channelRead(ExceptionLoggingHandler.java:37)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:797)
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:138)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.shared.protocol.netty.ConnectionFailedException: WireCommands.WrongHost(type=WRONG_HOST, requestId=1, segment=Scope/deena/0.#epoch.0, correctHost=, serverStackTrace=)
        ... 32 more
```

This issue needs to be further investigated, but it seems that remnants from the old Pravega cluster stored in ZooKeeper are conflicting with new clusters if they are given the same name. 

### Suggestions for an improvement

The operator should capture the "destroy" event and execute a clean up procedure that would eliminate any cluster-related data from ZooKeeper.

### Workaround

When destroying a Pravega cluster, also destroy the ZooKeeper cluster and volume claims. E.g. if your ZooKeeper cluster is called `zk` and you have 3 instances:

```
kubectl delete zk zk
kubectl delete pvc data-zk-0
kubectl delete pvc data-zk-1
kubectl delete pvc data-zk-2
```

Then, recreate the ZooKeeper cluster and the Pravega cluster.

**Comment by adrianmo** [comment]
This issue is a duplicate of #9

**Comment by adrianmo** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Operator: Zookeeper metadata cleanup](https://trello.com/c/ZTjUsGw8/64-operator-zookeeper-metadata-cleanup)
