### ISSUE TITLE
`java.nio.file.FileSystemException: /mnt/tier2/_system/_requeststream/1.#epoch.0$header: Invalid argument`  error when redeploying Pravega & Zookeeper cluster

### ISSUE THREAD

**Issue by deenav** [pravega/pravega-operator#93]
**Problem description**

When a Pravega Cluster & Zookeeper clusters are destroyed (including PVC) and recreated, a client is unable to communicate with old Tier-2 storage because of the conflicts as in ZK.

SegmentStore-0 error log

```2018-11-20 10:31:30,413 19806 [storage-io-4] ERROR i.p.s.s.h.h.PravegaRequestProcessor - [requestId=6] Error (Segment = '_system/_requeststream/1.#epoch.0', Operation = 'createSegment')
java.nio.file.FileSystemException: /mnt/tier2/_system/_requeststream/1.#epoch.0$header: Invalid argument                                                       
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)                                                                              
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)                                                                   
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.createFile(Files.java:632)
        at io.pravega.storage.filesystem.FileSystemStorage.doCreate(FileSystemStorage.java:283)                                                                
        at io.pravega.storage.filesystem.FileSystemStorage.lambda$create$5(FileSystemStorage.java:151)                                                         
        at io.pravega.storage.filesystem.FileSystemStorage.execute(FileSystemStorage.java:401)                                                                 
        at io.pravega.storage.filesystem.FileSystemStorage.create(FileSystemStorage.java:151)                                                                  
        at io.pravega.segmentstore.storage.rolling.RollingStorage.create(RollingStorage.java:257)                                                              
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$create$1(AsyncStorageWrapper.java:88)                                                    
        at io.pravega.segmentstore.storage.AsyncStorageWrapper.lambda$execute$13(AsyncStorageWrapper.java:184)                                                 
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)                                                                 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                             
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)                               
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)                                      
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                     
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                     
        at java.lang.Thread.run(Thread.java:748)
```

Client error log

```# ./pravega-benchmark/bin/pravega-benchmark --controller tcp://35.224.63.65:9090 --stream deena -producers 1 --writeonly false --randomkey true --size 100 -eventspersec 3000 --runtime 120            
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 35.224.63.65:9090
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] WARN io.pravega.client.ClientConfig - The credentials are not specified or could not be extracted.
[main] INFO io.pravega.client.stream.impl.ControllerImpl - Controller client connecting to server at 35.224.63.65:9090
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-8017196502695192802] Tagging client request (createScope-Scope).
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerResolverFactory - Updating client with controllers: [[addrs=[/35.224.63.65:9090], attrs={}]]
[grpc-default-executor-0] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-8017196502695192802] Scope created successfully: Scope
[main] INFO io.pravega.client.admin.impl.StreamManagerImpl - Creating scope/stream: Scope/deena with configuration: StreamConfiguration(scope=Scope, streamName=deena, scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null)
[StreamManager-Controller-1] INFO io.pravega.client.stream.impl.ControllerImpl - [requestId=-2060076304994449743] Tagging client request (createStream-Scope-deena).

[grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=-2060076304994449743] Failed to create stream: deena
[grpc-default-executor-1] WARN io.pravega.client.stream.impl.ControllerImpl - [requestId=-2060076304994449743] createStream failed: 
java.util.concurrent.CompletionException: io.pravega.client.stream.impl.ControllerFailureException: Failed to create stream: StreamConfiguration(scope=Scope, streamName=deena, scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:604)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onCompleted(ControllerImpl.java:985)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:416)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.pravega.client.stream.impl.ControllerFailureException: Failed to create stream: StreamConfiguration(scope=Scope, streamName=deena, scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null)
        at io.pravega.client.stream.impl.ControllerImpl.lambda$createStream$7(ControllerImpl.java:277)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        ... 24 more
java.lang.RuntimeException: io.pravega.client.stream.impl.ControllerFailureException: Failed to create stream: StreamConfiguration(scope=Scope, streamName=deena, scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null)
        at io.pravega.common.concurrent.Futures.getAndHandleExceptions(Futures.java:180)
        at io.pravega.client.admin.impl.StreamManagerImpl.createStream(StreamManagerImpl.java:63)
        at com.emc.pravega.perf.PravegaStreamHandler.create(PravegaStreamHandler.java:75)
        at com.emc.pravega.perf.PravegaPerfTest.main(PravegaPerfTest.java:121)
Caused by: io.pravega.client.stream.impl.ControllerFailureException: Failed to create stream: StreamConfiguration(scope=Scope, streamName=deena, scalingPolicy=ScalingPolicy(scaleType=FIXED_NUM_SEGMENTS, targetRate=0, scaleFactor=0, minNumSegments=1), retentionPolicy=null)
        at io.pravega.client.stream.impl.ControllerImpl.lambda$createStream$7(ControllerImpl.java:277)
        at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
        at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656)
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632)
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:1962)
        at io.pravega.client.stream.impl.ControllerImpl$RPCAsyncCallback.onCompleted(ControllerImpl.java:985)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:416)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:663)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:41)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:392)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:443)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:63)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:525)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$600(ClientCallImpl.java:446)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:557)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Suggestions for an improvement**

As per the discussion with @adrianmo, this issue needs to be further investigated. Maybe Pravega should create a unique instance ID and prepend that when storing Tier2 data to avoid conflicts.

**Workaround**

When destroying a Pravega cluster and the ZooKeeper cluster,  make sure to destroy Praevga-Tier2 volume claim as well. Eg: If your tier2 volume claim name is `pravega-tier2`
```
kubectl delete pravega-tier2
```
 Then, recreate Tier2 PVC along with ZooKeeper cluster and the Pravega cluster.

**Comment by adrianmo** [comment]
I'm closing this issue as it's not related to the operator. According to https://github.com/pravega/pravega/issues/3236, this issue is manifested when using an NFS volume provisioned by the nfs-server-provisioner, which contains a testing NFS server.

The proposed workaround is still valid and should be applied when using NFS volumes provisioned by nfs-server-provisioner.
